### ISSUE TITLE
pip problem in the new version of kali 

### ISSUE THREAD

**Issue by saberzaid** [s1l3nt78/sifter#10]
hello again 

thanks for the support and the script of fresh install 

again this is as you know new latest kali fresh install and apt updated as of today 

still facing 

/usr/bin/python: No module named pip

and pip2, pip3 error 

im login as user 

so do you think i should login as root user to fix this problem ? or is there any fix for this like for example no need to add sudo before the command as the tools installer not adding sudo as im login as normal user

**Comment by saberzaid** [comment]
as user , doing su then the root password i install again the fresh install script , pip3 is ok , pip its not 

error :sudo: pip: command not found,, maybe there is tool still not using python3 in your recon?

**Comment by saberzaid** [comment]
package github.com/subfinder/subfinder: no Go files in /root/go/src/github.com/subfinder/subfinder                                                                                          


requests 2.22.0 has requirement idna<2.9,>=2.5, but you'll have idna 2.9 which is incompatible.

**Comment by saberzaid** [comment]
Collecting BeautifulSoup==3.2.1
  Using cached BeautifulSoup-3.2.1.tar.gz (31 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-md_pukna/BeautifulSoup/setup.py'"'"'; __file__='"'"'/tmp/pip-install-md_pukna/BeautifulSoup/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-md_pukna/BeautifulSoup/pip-egg-info                                                                                                                        
         cwd: /tmp/pip-install-md_pukna/BeautifulSoup/                                                                                                                                      
    Complete output (6 lines):                                                                                                                                                              
    Traceback (most recent call last):                                                                                                                                                      
      File "<string>", line 1, in <module>                                                                                                                                                  
      File "/tmp/pip-install-md_pukna/BeautifulSoup/setup.py", line 22                                                                                                                      
        print "Unit tests have failed!"                                                                                                                                                     
              ^                                                                                                                                                                             
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Unit tests have failed!")?                                                                                     
    ----------------------------------------                                                                                                                                                
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by saberzaid** [comment]
Collecting requests>=2.20.0
  Downloading requests-2.23.0-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 842 kB/s 
Collecting ssdeep>=3.1.1
  Using cached ssdeep-3.4.tar.gz (110 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8qwmzq_h/ssdeep/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8qwmzq_h/ssdeep/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-8qwmzq_h/ssdeep/pip-egg-info                                                                                                                                             
         cwd: /tmp/pip-install-8qwmzq_h/ssdeep/                                                                                                                                             
    Complete output (13 lines):                                                                                                                                                             
    running egg_info                                                                                                                                                                        
    creating /tmp/pip-install-8qwmzq_h/ssdeep/pip-egg-info/ssdeep.egg-info                                                                                                                  
    writing /tmp/pip-install-8qwmzq_h/ssdeep/pip-egg-info/ssdeep.egg-info/PKG-INFO                                                                                                          
    writing dependency_links to /tmp/pip-install-8qwmzq_h/ssdeep/pip-egg-info/ssdeep.egg-info/dependency_links.txt                                                                          
    writing requirements to /tmp/pip-install-8qwmzq_h/ssdeep/pip-egg-info/ssdeep.egg-info/requires.txt                                                                                      
    writing top-level names to /tmp/pip-install-8qwmzq_h/ssdeep/pip-egg-info/ssdeep.egg-info/top_level.txt                                                                                  
    writing manifest file '/tmp/pip-install-8qwmzq_h/ssdeep/pip-egg-info/ssdeep.egg-info/SOURCES.txt'                                                                                       
    sh: 0: Can't open configure                                                                                                                                                             
    /bin/sh: 1: libtoolize: not found                                                                                                                                                       
    /bin/sh: 1: automake: not found                                                                                                                                                         
    Failed to reconfigure the project build.                                                                                                                                                
    Failed while building ssdeep lib with configure and make.                                                                                                                               
    Retry with autoreconf ...                                                                                                                                                               
    ----------------------------------------                                                                                                                                                
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by saberzaid** [comment]
the error above using the latest git version of the tool as of now

**Comment by s1l3nt78** [comment]
I have seen so i have reupdated the fresh-install script to sort out most of the issues.
"requests 2.22.0 has requirement idna<2.9,>=2.5, but you'll have idna 2.9 which is incompatible" <-- these types of warnings you can ignore as it poses no problem.
"package github.com/subfinder/subfinder: no Go files in /root/go/src/github.com/subfinder/subfinder" <-- this is unfortuntely a problem with subfinder not within my scripts so it can be ignored for now.
and the ssdeep error can be ignored as it is setup through apt instead of pip

Please re-clone and try again

**Comment by s1l3nt78** [comment]
have just re-updated

**Comment by s1l3nt78** [comment]
Please run sudo bash first and then the install. It mut be done with bash not sh

**Comment by s1l3nt78** [comment]
> as user , doing su then the root password i install again the fresh install script , pip3 is ok , pip its not
> 
> error :sudo: pip: command not found,, maybe there is tool still not using python3 in your recon?

There are tools still using python2 but the latest version of kali image is the only one that has this issue. Using a slightly older image and just updating from kali itself to the latest image keeps python2 pip installed correctly

**Comment by s1l3nt78** [comment]
I have just run the fresh-install on a brandnew kali image and everything installed correctly. As the tools themselves are ported over to python3 they will be fixed here as well. Any other issues lie on the individual tools themselves

**Comment by s1l3nt78** [comment]
Osmedues is having install issues as debian repos are being updated. Please wait for  few hours and just copy and paste the Osmedeus install commands from the script to install

**Comment by saberzaid** [comment]
ok let me know when the Osmedeus  and other problem fixed as much possible

**Comment by saberzaid** [comment]
> 
> 
> Collecting BeautifulSoup==3.2.1
> Using cached BeautifulSoup-3.2.1.tar.gz (31 kB)
> ERROR: Command errored out with exit status 1:
> command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-md_pukna/BeautifulSoup/setup.py'"'"'; **file**='"'"'/tmp/pip-install-md_pukna/BeautifulSoup/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-md_pukna/BeautifulSoup/pip-egg-info
> cwd: /tmp/pip-install-md_pukna/BeautifulSoup/
> Complete output (6 lines):
> Traceback (most recent call last):
> File "", line 1, in
> File "/tmp/pip-install-md_pukna/BeautifulSoup/setup.py", line 22
> print "Unit tests have failed!"
> ^
> SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Unit tests have failed!")?
> ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

have you seen this

**Comment by saberzaid** [comment]
> 
> 
> Collecting requests>=2.20.0
> Downloading requests-2.23.0-py2.py3-none-any.whl (58 kB)
> |████████████████████████████████| 58 kB 842 kB/s
> Collecting ssdeep>=3.1.1
> Using cached ssdeep-3.4.tar.gz (110 kB)
> ERROR: Command errored out with exit status 1:
> command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8qwmzq_h/ssdeep/setup.py'"'"'; **file**='"'"'/tmp/pip-install-8qwmzq_h/ssdeep/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-8qwmzq_h/ssdeep/pip-egg-info
> cwd: /tmp/pip-install-8qwmzq_h/ssdeep/
> Complete output (13 lines):
> running egg_info
> creating /tmp/pip-install-8qwmzq_h/ssdeep/pip-egg-info/ssdeep.egg-info
> writing /tmp/pip-install-8qwmzq_h/ssdeep/pip-egg-info/ssdeep.egg-info/PKG-INFO
> writing dependency_links to /tmp/pip-install-8qwmzq_h/ssdeep/pip-egg-info/ssdeep.egg-info/dependency_links.txt
> writing requirements to /tmp/pip-install-8qwmzq_h/ssdeep/pip-egg-info/ssdeep.egg-info/requires.txt
> writing top-level names to /tmp/pip-install-8qwmzq_h/ssdeep/pip-egg-info/ssdeep.egg-info/top_level.txt
> writing manifest file '/tmp/pip-install-8qwmzq_h/ssdeep/pip-egg-info/ssdeep.egg-info/SOURCES.txt'
> sh: 0: Can't open configure
> /bin/sh: 1: libtoolize: not found
> /bin/sh: 1: automake: not found
> Failed to reconfigure the project build.
> Failed while building ssdeep lib with configure and make.
> Retry with autoreconf ...
> ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

and this

**Comment by s1l3nt78** [comment]
yes like i dont dont worry ssdeep is setup through apt. please run "sudo apt-get install python3-ssdeep" and you can see for yourself

**Comment by s1l3nt78** [comment]
But i will Post in the release comments as soon as osmedeus is fixed
