### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by waton4617zx** [s1l3nt78/sifter#13]
sifter

/usr/sbin/sifter: line 801: syntax error near unexpected token `;'
/usr/sbin/sifter: line 801: `    	                    echo -e "\e[1;31m$name Dead\e[0m" && echo $name >> files/pingtest_raw.fail'
==================
/usr/sbin/sifter: line 803: syntax error near unexpected token `fi'
/usr/sbin/sifter: line 803: `    	                fi'

**Comment by s1l3nt78** [comment]
can i ask what exactly you were trying to do? or have you tried to edit the code? As i cant replicate this issue? 
Maybe try recloning?

**Comment by s1l3nt78** [comment]
Other open /opt/sifter/sifter in a code editor that shows line numbers.
Goto line 803 and make sure **fi**  is the only code on that line

**Comment by s1l3nt78** [comment]
I have found and fixed the issue, it should be working fine now with the new update
