### ISSUE TITLE
One Liner Change

### ISSUE THREAD

**Issue by hartescout** [s1l3nt78/sifter#30]
Simple fix. The one liner install needs to be changed from `wget https://github.com/s1l3nt78/sifter/releases/download/v10.4g/sifter_10.4_G.deb && sudo dpkg -i sifter_10.4_G.deb && sifter` to `wget https://github.com/s1l3nt78/sifter/releases/download/v10.4g/sifter_10.5_F.deb && sudo dpkg -i sifter_10.5_F.deb && sifter`

**Comment by s1l3nt78** [comment]
Haha right! Too much late night coding half asleep 🤣🙈 Thanks!
