### ISSUE TITLE
pls help me

### ISSUE THREAD

**Issue by phanthuthao** [s1l3nt78/sifter#33]
cat: /home/root/.config/.anon_status: No such file or directory

**Comment by s1l3nt78** [comment]
please dont run the install script or sifter as root.
Use a regular user and only give root permissions when it asks
Please copy and paste:
sudo rm -rf /opt/sifter; cd ~; git clone https://github.com/s1l3nt78/sifter; cd sifter; bash install.sh

**Comment by s1l3nt78** [comment]
Hi, if this issue is not followed-up on, it will be closed after 24hours of opening
